[font]
size = 16
offset = { x = 0, y = 12 }

[font.bold]
family = "Ubuntu Mono"
style = "Bold"

[font."bold_italic"]
family = "Ubuntu Mono"
style = "Bold Italic"

[font.italic]
family = "Ubuntu Mono"
style = "Italic"

[font.normal]
family = "Ubuntu Mono"
style = "Regular"

[window]
dynamic_padding = false
decorations = "full"
startup_mode = "Windowed"
padding = { x = 15, y = 20 }
dimensions = { columns = 80, lines = 30 }

[cursor]
style = { shape = "Underline", blinking = "Off"}
